# Generated by Django 3.2.5 on 2022-08-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='tax_ID_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
