# Generated by Django 3.2.5 on 2022-09-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_cart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
